version: '2.3'

services:
  files:
    build:
      context: .
    volumes:
      - "./:/service"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432
      - MASTER_KEY=3435tdfsdudebussylmaoxxt43
      - REDIS_URL=redis://redis
      - DOMAIN=localhost
      - SITE_NAME=Drama
      - GIPHY_KEY=3435tdfsdudebussylmaoxxt43
      - DISCORD_SERVER_ID=3435tdfsdudebussylmaoxxt43
      - DISCORD_CLIENT_ID=3435tdfsdudebussylmaoxxt43
      - DISCORD_CLIENT_SECRET=3435tdfsdudebussylmaoxxt43
      - DISCORD_BOT_TOKEN=3435tdfsdudebussylmaoxxt43
      #- HCAPTCHA_SITEKEY=3435tdfsdudebussylmaoxxt43
      - HCAPTCHA_SECRET=3435tdfsdudebussylmaoxxt43
      - YOUTUBE_KEY=3435tdfsdudebussylmaoxxt43
      #- PUSHER_ID=3435tdfsdudebussylmaoxxt43
      - PUSHER_KEY=3435tdfsdudebussylmaoxxt43
      - IMGUR_KEY=3435tdfsdudebussylmaoxxt43
      - SPAM_SIMILARITY_THRESHOLD=0.5
      - SPAM_URL_SIMILARITY_THRESHOLD=0.1
      - SPAM_SIMILAR_COUNT_THRESHOLD=10
      - COMMENT_SPAM_SIMILAR_THRESHOLD=0.5
      - COMMENT_SPAM_COUNT_THRESHOLD=10
      - READ_ONLY=0
      - BOT_DISABLE=0
      - DEFAULT_TIME_FILTER=all
      - DEFAULT_THEME=midnight
      - DEFAULT_COLOR=ff66ac
      - GUMROAD_TOKEN=3435tdfsdudebussylmaoxxt43
      - GUMROAD_LINK=https://marsey1.gumroad.com/l/tfcvri
      - GUMROAD_ID=tfcvri
      - CARD_VIEW=1
      - DISABLE_DOWNVOTES=0
      - DUES=0
      - MAIL_USERNAME=blahblahblah@gmail.com
      - MAIL_PASSWORD=3435tdfsdudebussylmaoxxt43
      - DESCRIPTION=rdrama.net caters to drama in all forms such as Real life, videos, photos, gossip, rumors, news sites, Reddit, and Beyond™. There isn't drama we won't touch, and we want it all!
      - CF_KEY=3435tdfsdudebussylmaoxxt43
      - CF_ZONE=3435tdfsdudebussylmaoxxt43
    links:
      - "redis"
      - "postgres"
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    # command: ["postgres", "-c", "log_statement=all"]
    # uncomment this if u wanna output all SQL queries to the console
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
      - "./seed-db.sql:/docker-entrypoint-initdb.d/10-seed-db.sql"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"